---
title: "Outbreak Dashboard"
author: "Mikyas Duga - BoardSource"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
  self_contained: true
  mode: selfcontained
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(incidence2)
library(plotly)
library(rio)

linelist <- import("C:/Users/mikyas.duga/OneDrive - BoardSource/Documents/R/MDdashboard/linelist_cleaned.rds")
```

Column {data-width=650}
-----------------------------------------------------------------------
#Executive Summary

This dashboard is a flexdashboard production. Damn son where'd you find this?



# Cases By Hospital {data-navmenu="Cases"}

```{r}
linelist %>%
  count(hospital) %>%
  rename("Hospital"= hospital,
         "cases" = n) %>%
  knitr::kable()
```


# DataTable {data-navmenu="Case Counts"}

```{r}
DT::datatable(linelist, 
              rownames = FALSE, 
              options = list(pageLength = 5, scrollX = TRUE), 
              class = 'white-space: nowrap' )
```

# Incidence Summary {data-navmenu="Incidence Plot"}

```{r}
age_outbreak <- incidence(linelist, date_onset, "week", groups = age_cat)
plot(age_outbreak, fill = age_cat, col_pal = muted, title = "")%>% 
  plotly::ggplotly()
```

